/* ============================================================
 *  打工充能站 · MBTI 数据库
 *  16 型谐音梗昵称 + 运势倾向 + 梗图文案 + 职场建议
 * ============================================================ */

const MBTI_DATA = {
  INTJ: {
    name: "建筑师",
    nickname: "卷王之王",
    pun: "I Need To 卷",
    group: "analyst",
    color: "#6c5ce7",
    bgGradient: "linear-gradient(135deg, #6c5ce7, #a29bfe)",
    emoji: "♟️",
    traits: ["独立思考", "战略大师", "效率狂魔", "社恐晚期"],
    element: "风",
    luckyColor: "深紫",
    luckyNumber: 7,
    fortuneBias: "今天的你脑子转得比服务器还快，适合做长期规划——但记得抬头看看同事的脸色，别卷得太明显。",
    meme: "INTJ的计划表精确到秒，\n人际关系精确到...\n算了不规划了反正他们听不懂",
    challenges: [
      "花5分钟和同事闲聊一句不关于工作的话（我知道这比写代码还难）",
      "把你那完美的计划分享给团队一个，让凡人也能参与",
      "今天允许一件事不在计划内发生，天塌不下来",
      "对一个不合理的需求说'我再想想'而不是直接推翻对方",
      "在工位上闭眼冥想3分钟，假装在思考其实是在放空"
    ],
    workTip: "你的战略眼光是优势，但记住——团队执行力也需要你的耐心沟通。今天适合把脑中蓝图翻译成人话。",
    energySource: "深度思考",
    weakSpot: "社交电量",
    dailyPraise: "今天又是被自己智商帅醒的一天！"
  },
  INTP: {
    name: "逻辑学家",
    nickname: "思考型咸鱼",
    pun: "I Need To 瘫",
    group: "analyst",
    color: "#00cec9",
    bgGradient: "linear-gradient(135deg, #00cec9, #55efc4)",
    emoji: "🔬",
    traits: ["逻辑鬼才", "好奇心爆棚", "拖延冠军", "辩论爱好者"],
    element: "风",
    luckyColor: "青绿",
    luckyNumber: 3,
    fortuneBias: "今天灵感像开了闸一样，但执行力可能在被窝里。先把最简单的任务做了，启动了就好办。",
    meme: "INTP想通了宇宙的终极答案\n但懒得写下来\n'反正我知道就行了'",
    challenges: [
      "把脑子里那个绝妙想法写下来，哪怕只是一句话",
      "选一个拖延了3天以上的任务，只做5分钟",
      "今天不跟任何人辩论，即使对方说1+1=3也微笑点头",
      "把桌面收拾一下，让灵感有地方落脚",
      "用一个你的知识点帮助一个同事，深藏功与名"
    ],
    workTip: "你的分析能力无人能及，但想法不落地就是空气。今天挑一个想法，哪怕做得很糙也要让它成型。",
    energySource: "探索新知",
    weakSpot: "执行落地",
    dailyPraise: "脑洞虽大，今天也要钻出来一个！"
  },
  ENTJ: {
    name: "指挥官",
    nickname: "天生卷王",
    pun: "Everyone Needs 我的计划",
    group: "analyst",
    color: "#e17055",
    bgGradient: "linear-gradient(135deg, #e17055, #fab1a0)",
    emoji: "⚔️",
    traits: ["天生领袖", "目标导向", "效率至上", "不废话"],
    element: "风",
    luckyColor: "正红",
    luckyNumber: 1,
    fortuneBias: "今天的你气场两米八，适合推动搁置的项目。注意别把下属的活也干了——学会放权也是一种力量。",
    meme: "ENTJ的口头禅：\n'这事我三分钟搞定了'\n（团队在身后瑟瑟发抖）",
    challenges: [
      "今天把一件事交给别人做，并且忍住不插手",
      "对一个下属说一句真诚的夸奖，不要带'但是'",
      "花10分钟听一个同事完整说完想法，不打断",
      "今天允许一个'不够完美但够用'的方案通过",
      "给自己定一个下班时间，到点就走"
    ],
    workTip: "你的执行力是团队引擎，但引擎也需要保养。今天试着'少做一点'，把舞台让给别人。",
    energySource: "征服目标",
    weakSpot: "情绪感知",
    dailyPraise: "江山是你打的，但今天也要歇歇！"
  },
  ENTP: {
    name: "辩论家",
    nickname: "杠精本精",
    pun: "Everyone Needs 挑刺",
    group: "analyst",
    color: "#fdcb6e",
    bgGradient: "linear-gradient(135deg, #fdcb6e, #ffeaa7)",
    emoji: "🃏",
    traits: ["脑洞王者", "杠精转世", "创意永动机", "计划？什么计划"],
    element: "风",
    luckyColor: "明黄",
    luckyNumber: 5,
    fortuneBias: "今天你的创意能闪瞎全场，但执行可能还在路上。先记录灵感，再挑一个落地——别又开了十个头。",
    meme: "ENTP：我有一个绝妙的idea！\n同事：上次那个呢？\nENTP：什么上次？这是新的！",
    challenges: [
      "今天完成一个之前开了头但没做完的项目",
      "提出一个新想法的同时，附上一个执行步骤",
      "忍住一次抬杠的冲动，先说'你说得有道理'",
      "把你的创意整理成3条发给领导，别只说不写",
      "找一个你平时看不惯的流程，想想怎么优化它"
    ],
    workTip: "你的创意是金矿，但金矿也需要开采。今天选一个点子，从'说'变成'做'。",
    energySource: "思维碰撞",
    weakSpot: "收尾能力",
    dailyPraise: "你的嘴是武器，今天用它来夸人！"
  },
  INFJ: {
    name: "提倡者",
    nickname: "预言家卷王",
    pun: "I Notice 佛系假象",
    group: "diplomat",
    color: "#0984e3",
    bgGradient: "linear-gradient(135deg, #0984e3, #74b9ff)",
    emoji: "🔮",
    traits: ["读心术持有者", "理想主义", "外冷内热", "过度共情"],
    element: "风",
    luckyColor: "海蓝",
    luckyNumber: 9,
    fortuneBias: "今天你的直觉准得可怕，相信第一感觉。但别一个人扛太多——该求助就求助，你的肩膀也需要休息。",
    meme: "INFJ：我没事\n内心：已经在脑补\n八百种世界毁灭的方式了",
    challenges: [
      "今天对一件事说'不'，不用解释太多理由",
      "把你的一个预感告诉信任的同事，别只闷在心里",
      "花10分钟纯粹放空，不看手机不想工作",
      "写下三个今天值得感恩的小事，哪怕很小",
      "主动找一个人聊聊天，但这次不用猜对方心思"
    ],
    workTip: "你的洞察力是天赋，但别让共情成为负担。今天设定一个'情绪边界'，先照顾好自己的能量。",
    energySource: "意义感",
    weakSpot: "情绪过载",
    dailyPraise: "你的善良是超能力，但今天先充自己的电！"
  },
  INFP: {
    name: "调停者",
    nickname: "emo小天才",
    pun: "I Need 佛 Power",
    group: "diplomat",
    color: "#fd79a8",
    bgGradient: "linear-gradient(135deg, #fd79a8, #fab1a0)",
    emoji: "🦋",
    traits: ["浪漫至死", "共情怪物", "白日梦想家", "社恐但话痨"],
    element: "风",
    luckyColor: "粉色",
    luckyNumber: 4,
    fortuneBias: "今天灵感像泡泡一样冒，但可能被现实戳破几个也没关系。记住你的感受力是天赋，不是矫情。",
    meme: "INFP的日常：\n上午：世界真好\n下午：世界好糟\n晚上：写一首诗\n凌晨：我是谁",
    challenges: [
      "把今天的情绪写下来，哪怕只是一段碎碎念",
      "做一件让你觉得'有意义'的小事，不求回报",
      "今天不在脑内预演失败的剧本，只演成功的那一版",
      "找一个你欣赏的同事，真诚地夸一句",
      "允许自己今天不那么'完美'，及格就很棒了"
    ],
    workTip: "你的共情力和创造力是稀缺品。今天别藏了，把你的想法大胆说出来——世界需要你的温柔。",
    energySource: "内心世界",
    weakSpot: "现实碰撞",
    dailyPraise: "你的敏感是雷达，不是bug！"
  },
  ENFJ: {
    name: "主人公",
    nickname: "热心大妈/大哥",
    pun: "Everyone Needs 关怀",
    group: "diplomat",
    color: "#00b894",
    bgGradient: "linear-gradient(135deg, #00b894, #55efc4)",
    emoji: "🌟",
    traits: ["人间小太阳", "团建发起人", "读空气大师", "操心命"],
    element: "风",
    luckyColor: "翠绿",
    luckyNumber: 6,
    fortuneBias: "今天你是团队的粘合剂，但别忘了粘合剂也需要补充能量。在照顾别人之前，先给自己倒杯水。",
    meme: "ENFJ：你们都还好吗？\n同事：好着呢\nENFJ：不我觉得你不好\n让我来帮你！",
    challenges: [
      "今天先照顾自己一次，再照顾别人",
      "对别人的请求说一次'我看看时间'，不立刻答应",
      "给自己安排30分钟独处时间，不回消息",
      "把你想帮别人的话，先对自己说一遍",
      "今天不主动组织任何活动，被动参与就好"
    ],
    workTip: "你的感染力能点亮整个办公室。但今天把聚光灯让给别人，你退到幕后充个电。",
    energySource: "人际联结",
    weakSpot: "自我关怀",
    dailyPraise: "你是团队的太阳，但太阳也要落山休息！"
  },
  ENFP: {
    name: "竞选者",
    nickname: "快乐修勾",
    pun: "Everyone Needs 拍一拍",
    group: "diplomat",
    color: "#e84393",
    bgGradient: "linear-gradient(135deg, #e84393, #fd79a8)",
    emoji: "🌈",
    traits: ["社交天花板", "灵感喷射机", "三分钟热度", "人间橡皮糖"],
    element: "风",
    luckyColor: "玫红",
    luckyNumber: 8,
    fortuneBias: "今天你的能量能感染整层楼，但记得给社恐同事留点呼吸空间。你的热情是礼物，适度释放更珍贵。",
    meme: "ENFP：我超喜欢这个！\n（三分钟后）\nENFP：我超喜欢这个新的！\n旧的那个：？",
    challenges: [
      "今天专注完成一件事再开始下一件",
      "给一个不熟的同事主动打个招呼，释放你的魔力",
      "把你跳脱的想法用便签记下来，别让灵感溜走",
      "今天试着安静工作30分钟，体验一下'沉默的力量'",
      "找一个你三分钟热度放弃的事，今天捡起来做5分钟"
    ],
    workTip: "你的热情是团队的燃料。今天把燃料精准投放——集中火力攻克一个目标，而不是四处点火。",
    energySource: "新鲜感",
    weakSpot: "持续专注",
    dailyPraise: "你的快乐会传染，今天传染一个吧！"
  },
  ISTJ: {
    name: "物流师",
    nickname: "表格成精",
    pun: "I See 数据",
    group: "sentinel",
    color: "#2d3436",
    bgGradient: "linear-gradient(135deg, #2d3436, #636e72)",
    emoji: "📋",
    traits: ["计划信徒", "细节控", "靠谱本谱", "规则守护者"],
    element: "土",
    luckyColor: "深灰",
    luckyNumber: 2,
    fortuneBias: "今天你的条理性拯救全场。但偶尔允许计划外的事发生——意外里也藏着惊喜。",
    meme: "ISTJ的工位：\n文件按颜色分类\n笔按角度排列\n同事：借支笔\nISTJ：登记一下",
    challenges: [
      "今天允许一个计划外的变化，不焦虑",
      "尝试一种新的工作方法，即使老方法也挺好",
      "对同事的一个错误温和以待，不立刻纠正",
      "花5分钟跟同事聊聊非工作话题",
      "今天把一个'应该做的事'换成'想做的事'"
    ],
    workTip: "你的靠谱是团队的定海神针。今天试着在'标准'之外留一点弹性的空间。",
    energySource: "秩序感",
    weakSpot: "灵活变通",
    dailyPraise: "世界因你的Excel而运转！"
  },
  ISFJ: {
    name: "守卫者",
    nickname: "好人卡收集器",
    pun: "I Serve 饭局",
    group: "sentinel",
    color: "#a29bfe",
    bgGradient: "linear-gradient(135deg, #a29bfe, #dfe6e9)",
    emoji: "🛡️",
    traits: ["默默付出型", "细节暖心", "老好人", "记忆超强"],
    element: "土",
    luckyColor: "薰衣草紫",
    luckyNumber: 6,
    fortuneBias: "今天你的细心帮了大忙，但别把自己累坏了。默默付出也需要被看见——试着说出来。",
    meme: "ISFJ：没关系我来吧\n（第三次了）\nISFJ：没关系我来吧\n（已经第十次了）\nISFJ内心：求求你们自己来吧",
    challenges: [
      "今天对一件事说'这个我不太方便'，不用道歉",
      "把你默默做的事列个清单，让别人知道你的贡献",
      "给自己安排一杯好喝的，犒劳默默付出的自己",
      "今天不主动揽活，等别人来求助",
      "把想说的但一直没说的话，温和地说出来一次"
    ],
    workTip: "你的细心和付出是团队的地基。但今天试着把'我来做'换成'你来试试'。",
    energySource: "被需要感",
    weakSpot: "自我表达",
    dailyPraise: "你不是透明人，你的付出有人看见！"
  },
  ESTJ: {
    name: "总经理",
    nickname: "鸡血播报员",
    pun: "Everything 按时",
    group: "sentinel",
    color: "#d63031",
    bgGradient: "linear-gradient(135deg, #d63031, #ff7675)",
    emoji: "📌",
    traits: ["执行力怪兽", "秩序维护者", "效率监督员", "不解释型"],
    element: "土",
    luckyColor: "正红",
    luckyNumber: 1,
    fortuneBias: "今天你的推进力能推动停滞的项目。但注意——人不是机器，偶尔允许'低效'的沟通存在。",
    meme: "ESTJ：9点开会\n同事：9点02到\nESTJ：你已经迟到了\n同事：还没到9点啊\nESTJ：在我的世界里已经迟到了",
    challenges: [
      "今天在催进度前先问一句'有遇到困难吗'",
      "对一个迟到的回复多等5分钟再催",
      "用'你觉得怎么样'代替'按我说的做'",
      "今天发现一个同事的闪光点并告诉他",
      "允许一件事用你觉得'低效'但别人觉得舒适的方式完成"
    ],
    workTip: "你的执行力是团队的引擎。今天把'推动'换成'陪伴'，有时候慢一点反而走得更远。",
    energySource: "完成感",
    weakSpot: "情感连接",
    dailyPraise: "团队因你而高效，今天也夸夸自己！"
  },
  ESFJ: {
    name: "执政官",
    nickname: "茶水间之花",
    pun: "Everyone 三顿饭 OK",
    group: "sentinel",
    color: "#ff7675",
    bgGradient: "linear-gradient(135deg, #ff7675, #fab1a0)",
    emoji: "☕",
    traits: ["社交达人", "暖场专家", "关怀专员", "气氛组组长"],
    element: "土",
    luckyColor: "珊瑚粉",
    luckyNumber: 3,
    fortuneBias: "今天你的热情让办公室温度+5度。但记得给自己也泡杯茶——照顾别人之前先照顾自己。",
    meme: "ESFJ：今天谁生日？\n没人过生日\nESFJ：那我来定个蛋糕\n大家也需要开心一下！",
    challenges: [
      "今天给自己泡一杯好茶/咖啡，慢慢喝完",
      "对别人的事少操心一次，专注自己的事",
      "今天不主动组织任何事，享受被动参与",
      "把关心的能量分一半给自己",
      "对一件你一直想吐槽的事，温和地说出来"
    ],
    workTip: "你的温暖是团队的恒温器。今天把温度调到'舒适'而不是'热情'——包括对自己。",
    energySource: "人际和谐",
    weakSpot: "自我边界",
    dailyPraise: "你是办公室的温度，今天给自己也加加温！"
  },
  ISTP: {
    name: "鉴赏家",
    nickname: "闷骚手艺人",
    pun: "I See 技术活",
    group: "explorer",
    color: "#636e72",
    bgGradient: "linear-gradient(135deg, #636e72, #b2bec3)",
    emoji: "🔧",
    traits: ["动手大师", "冷静应对", "独狼型选手", "话少活好"],
    element: "土",
    luckyColor: "钢灰",
    luckyNumber: 5,
    fortuneBias: "今天你的实操能力解决问题如切菜。但偶尔把经验分享出来——你的沉默可能被误读为冷漠。",
    meme: "ISTP：修好了\n同事：怎么修的？\nISTP：就是...修了\n同事：？？？\nISTP已经去修下一个了",
    challenges: [
      "今天把你解决一个问题的思路说给同事听",
      "主动帮一个同事解决一个技术难题",
      "今天多说两句话，让同事知道你在想什么",
      "尝试用文字记录一次你的操作步骤",
      "在团队讨论时发表一次你的看法"
    ],
    workTip: "你的实操能力是团队的瑞士军刀。今天把'做'和'说'结合——分享让能力加倍。",
    energySource: "动手解决",
    weakSpot: "知识传递",
    dailyPraise: "你的手是金子做的，今天也让嘴动一动！"
  },
  ISFP: {
    name: "探险家",
    nickname: "佛系艺术家",
    pun: "I See 美的地方",
    group: "explorer",
    color: "#55efc4",
    bgGradient: "linear-gradient(135deg, #55efc4, #81ecec)",
    emoji: "🎨",
    traits: ["审美天花板", "佛系打工人", "随性而为", "内心丰富"],
    element: "土",
    luckyColor: "薄荷绿",
    luckyNumber: 7,
    fortuneBias: "今天你的审美和灵感在线。但别只藏在心里——把你的创意亮出来，哪怕只是一个配色建议。",
    meme: "ISFP：这个设计可以更好\n内心已经改了八百版\n嘴上：还行吧\n同事：那就这样？\nISFP：嗯（心在滴血）",
    challenges: [
      "今天大胆说出你对某件事的审美看法",
      "把工位装饰一下，提升自己的幸福感",
      "用你擅长的美感帮一个同事优化一个东西",
      "今天做一件纯粹因为'好看'而做的事",
      "把你的灵感画/写下来，不用完美"
    ],
    workTip: "你的审美和创造力是宝藏。今天别藏私——你的'还行'其实是'很棒'，大胆表达。",
    energySource: "美的体验",
    weakSpot: "自我展示",
    dailyPraise: "你的眼睛会发光，今天让它亮给别人看！"
  },
  ESTP: {
    name: "企业家",
    nickname: "整活达人",
    pun: "Everybody 速 速 速",
    group: "explorer",
    color: "#feca57",
    bgGradient: "linear-gradient(135deg, #feca57, #ff9f43)",
    emoji: "⚡",
    traits: ["行动派", "冒险家", "现充代表", "规则？什么规则"],
    element: "土",
    luckyColor: "橙金",
    luckyNumber: 9,
    fortuneBias: "今天你的行动力碾压犹豫。但冲之前停三秒——有时候'快'不如'准'。",
    meme: "ESTP：我先干了你们随意\n同事：等等我们还没...\nESTP已经做完了\n同事：......",
    challenges: [
      "今天在行动前多想三秒钟",
      "把你的行动成果整理记录下来，别只做不说",
      "今天等一个慢热的同事跟上你的节奏",
      "尝试一个需要耐心才能完成的小任务",
      "把你的冒险精神用在创新上而不是打破规则上"
    ],
    workTip: "你的行动力是团队的加速器。今天把'冲'换成'带'——带别人一起冲比一个人冲更有效。",
    energySource: "即时行动",
    weakSpot: "耐心沉淀",
    dailyPraise: "你的速度是闪电，今天也等一等雷声！"
  },
  ESFP: {
    name: "表演者",
    nickname: "派对永动机",
    pun: "Everybody 烧 烧 烧（烧气氛）",
    group: "explorer",
    color: "#ff9ff3",
    bgGradient: "linear-gradient(135deg, #ff9ff3, #f368e0)",
    emoji: "🎉",
    traits: ["气氛组组长", "活在当下", "社交蝴蝶", "快乐制造机"],
    element: "土",
    luckyColor: "亮粉",
    luckyNumber: 3,
    fortuneBias: "今天你的存在就是办公室的BGM。但偶尔也需要静音模式——安静的你也很迷人。",
    meme: "ESFP：今天也要元气满满！\n同事：（还没睡醒）\nESFP：来跟我一起嗨！\n同事：让我静静\nESFP：静什么静！嗨起来！",
    challenges: [
      "今天给自己一段'静音时间'，不社交不互动",
      "把社交能量分一部分给深度工作",
      "今天认真听一个同事说话，不只是活跃气氛",
      "做一件'不好玩但该做'的事",
      "把你的快乐用一个具体的方式记录下来"
    ],
    workTip: "你的活力是团队的维他命。今天试着从'氛围担当'切换到'深度担当'——两面的你都很棒。",
    energySource: "当下体验",
    weakSpot: "深度专注",
    dailyPraise: "你是行走的多巴胺，今天也给自己补补！"
  }
};

// MBTI 分组信息
const MBTI_GROUPS = {
  analyst: { name: "分析家", desc: "理性卷王团", emoji: "🧠" },
  diplomat: { name: "外交官", desc: "共情小天才", emoji: "💖" },
  sentinel: { name: "守护者", desc: "靠谱担当团", emoji: "🛡️" },
  explorer: { name: "探险家", desc: "行动永动机", emoji: "⚡" }
};

// MBTI 测试题（简化版快速测试）
const MBTI_QUESTIONS = [
  { dim: "EI", q: "团建结束后的你：", a: "电量充满，还想再来一轮", b: "急需独处回血，谁都别跟我说话" },
  { dim: "EI", q: "遇到问题时你倾向于：", a: "找人聊聊讨论一下", b: "自己先想想理一理" },
  { dim: "SN", q: "你更喜欢的工作方式：", a: "有明确的步骤和流程", b: "留有创造和想象的空间" },
  { dim: "SN", q: "你更相信：", a: "经验和事实", b: "直觉和灵感" },
  { dim: "TF", q: "做决定时你更看重：", a: "逻辑和效率", b: "感受和影响" },
  { dim: "TF", q: "同事跟你诉苦，你第一反应：", a: "帮他分析问题找方案", b: "先共情安慰再说" },
  { dim: "JP", q: "你的周末计划：", a: "提前安排得明明白白", b: "走一步看一步随机应变" },
  { dim: "JP", q: "面对deadline：", a: "提前搞定心里踏实", b: "极限操作效率最高" }
];
